// Embeds scripts/herdr-apns-notifier.py into the app, which installs it on a
// host over SSH. Run after changing the script:  node scripts/embed-watcher.mjs
// A test fails while the two differ.
import { readFileSync, writeFileSync } from 'node:fs';

const script = readFileSync(new URL('./herdr-apns-notifier.py', import.meta.url), 'utf8');
const version = /^WATCHER_VERSION = (\d+)$/m.exec(script)?.[1];
if (version === undefined) throw new Error('herdr-apns-notifier.py has no WATCHER_VERSION line');
const base64 = Buffer.from(script, 'utf8').toString('base64');

writeFileSync(
  new URL('../src/lib/notifier/watcherScript.ts', import.meta.url),
  [
    '// Generated by scripts/embed-watcher.mjs from scripts/herdr-apns-notifier.py.',
    '// Do not edit; change the script and run `node scripts/embed-watcher.mjs`.',
    '',
    `export const WATCHER_VERSION = ${version};`,
    '',
    '/** The watcher script, base64, which is also how it travels to the host. */',
    `export const WATCHER_SCRIPT_BASE64 = '${base64}';`,
    '',
  ].join('\n')
);
